const cards = {
  '2C': require('./clubs_2.png'),
  '3C': require('./clubs_3.png'),
  '4C': require('./clubs_4.png'),
  '5C': require('./clubs_5.png'),
  '6C': require('./clubs_6.png'),
  '7C': require('./clubs_7.png'),
  '8C': require('./clubs_8.png'),
  '9C': require('./clubs_9.png'),
  '10C': require('./clubs_10.png'),
  'JC': require('./clubs_jack.png'),
  'QC': require('./clubs_queen.png'),
  'KC': require('./clubs_king.png'),
  'AC': require('./clubs_ace.png'),

  '2D': require('./diamonds_2.png'),
  '3D': require('./diamonds_3.png'),
  '4D': require('./diamonds_4.png'),
  '5D': require('./diamonds_5.png'),
  '6D': require('./diamonds_6.png'),
  '7D': require('./diamonds_7.png'),
  '8D': require('./diamonds_8.png'),
  '9D': require('./diamonds_9.png'),
  '10D': require('./diamonds_10.png'),
  'JD': require('./diamonds_jack.png'),
  'QD': require('./diamonds_queen.png'),
  'KD': require('./diamonds_king.png'),
  'AD': require('./diamonds_ace.png'),

  '2H': require('./hearts_2.png'),
  '3H': require('./hearts_3.png'),
  '4H': require('./hearts_4.png'),
  '5H': require('./hearts_5.png'),
  '6H': require('./hearts_6.png'),
  '7H': require('./hearts_7.png'),
  '8H': require('./hearts_8.png'),
  '9H': require('./hearts_9.png'),
  '10H': require('./hearts_10.png'),
  'JH': require('./hearts_jack.png'),
  'QH': require('./hearts_queen.png'),
  'KH': require('./hearts_king.png'),
  'AH': require('./hearts_ace.png'),

  '2S': require('./spades_2.png'),
  '3S': require('./spades_3.png'),
  '4S': require('./spades_4.png'),
  '5S': require('./spades_5.png'),
  '6S': require('./spades_6.png'),
  '7S': require('./spades_7.png'),
  '8S': require('./spades_8.png'),
  '9S': require('./spades_9.png'),
  '10S': require('./spades_10.png'),
  'JS': require('./spades_jack.png'),
  'QS': require('./spades_queen.png'),
  'KS': require('./spades_king.png'),
  'AS': require('./spades_ace.png'),

  'BACK': require('./back_1.png')
};

export default cards;
